Repository IceButler/IceButler_Server, pull requests merged in 2024-07, with the labels that each got.

#315 #312 유저 스웨거 작성
  src/main/java/com/example/icebutler_server/user/controller/UserAuthController.java
  src/main/java/com/example/icebutler_server/user/controller/UserController.java
  src/main/java/com/example/icebutler_server/user/dto/LoginUserReq.java
  src/main/java/com/example/icebutler_server/user/dto/request/PatchProfileReq.java
  src/main/java/com/example/icebutler_server/user/dto/request/PostNicknameReq.java
  src/main/java/com/example/icebutler_server/user/dto/response/MyNotificationRes.java
  src/main/java/com/example/icebutler_server/user/dto/response/MyProfileRes.java
  src/main/java/com/example/icebutler_server/user/dto/response/NickNameRes.java
  src/main/java/com/example/icebutler_server/user/dto/response/PostNickNameRes.java
  src/main/java/com/example/icebutler_server/user/dto/response/PostUserRes.java
  src/main/java/com/example/icebutler_server/user/service/UserService.java
  src/main/java/com/example/icebutler_server/user/service/UserServiceImpl.java
Labels: 📝 docs

#319 #318 cicd 설정
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
  src/main/resources/application.yml
Labels: 🐳 CI/CD

#320 #318 도커 파일 수정
  Dockerfile
Labels: 🐳 CI/CD

#321 #318 도커 파일 수정
  Dockerfile
Labels: 🐳 CI/CD

#322 #318 cicd 설정 수정
  .gitignore
  src/main/java/com/example/icebutler_server/fridge/controller/FridgeController.java
Labels: 🐳 CI/CD

#324 #323 refactor: exception 구조 변경
  src/main/java/com/example/icebutler_server/admin/controller/AdminController.java
  src/main/java/com/example/icebutler_server/admin/controller/AdminExceptionController.java
  src/main/java/com/example/icebutler_server/cart/controller/CartController.java
  src/main/java/com/example/icebutler_server/cart/controller/CartExceptionController.java
  src/main/java/com/example/icebutler_server/food/controller/FoodController.java
  src/main/java/com/example/icebutler_server/food/controller/FoodExceptionController.java
  src/main/java/com/example/icebutler_server/fridge/controller/FridgeController.java
  src/main/java/com/example/icebutler_server/fridge/controller/FridgeExceptionController.java
  src/main/java/com/example/icebutler_server/global/controller/ExceptionController.java
  src/main/java/com/example/icebutler_server/global/dto/response/ResponseCustom.java
  src/main/java/com/example/icebutler_server/global/exception/BaseException.java
  src/main/java/com/example/icebutler_server/global/exception/ExceptionAdvice.java
  src/main/java/com/example/icebutler_server/global/exception/ReturnCode.java
  src/main/java/com/example/icebutler_server/user/controller/UserAuthController.java
  src/main/java/com/example/icebutler_server/user/controller/UserController.java
  src/main/java/com/example/icebutler_server/user/controller/UserExceptionController.java
Labels: ♻️ refactor

#326 #325 food, cart, user exception 구조 변경 및 assembler 삭제
  src/main/java/com/example/icebutler_server/admin/dto/assembler/AdminAssembler.java
  src/main/java/com/example/icebutler_server/admin/service/AdminServiceImpl.java
  src/main/java/com/example/icebutler_server/cart/controller/CartController.java
  src/main/java/com/example/icebutler_server/cart/dto/assembler/CartAssembler.java
  src/main/java/com/example/icebutler_server/cart/dto/assembler/CartFoodAssembler.java
  src/main/java/com/example/icebutler_server/cart/entity/Cart.java
  src/main/java/com/example/icebutler_server/cart/entity/CartFood.java
  src/main/java/com/example/icebutler_server/cart/exception/CartFoodNotFoundException.java
  src/main/java/com/example/icebutler_server/cart/exception/CartNotFoundException.java
  src/main/java/com/example/icebutler_server/cart/service/CartServiceImpl.java
  src/main/java/com/example/icebutler_server/food/controller/FoodController.java
  src/main/java/com/example/icebutler_server/food/dto/assembler/FoodAssembler.java
  src/main/java/com/example/icebutler_server/food/entity/Food.java
  src/main/java/com/example/icebutler_server/food/entity/FoodCategory.java
  src/main/java/com/example/icebutler_server/food/entity/FoodDeleteStatus.java
  src/main/java/com/example/icebutler_server/food/exception/BarcodeFoodNotFoundException.java
  src/main/java/com/example/icebutler_server/food/exception/DuplicateFoodNameException.java
  src/main/java/com/example/icebutler_server/food/exception/FoodCategoryNotFoundException.java
  src/main/java/com/example/icebutler_server/food/exception/FoodDeleteStatusNotFoundException.java
  src/main/java/com/example/icebutler_server/food/exception/FoodNameNotFoundException.java
  src/main/java/com/example/icebutler_server/food/service/FoodServiceImpl.java
  src/main/java/com/example/icebutler_server/fridge/exception/CannotDeleteFridgeException.java
  src/main/java/com/example/icebutler_server/fridge/service/FridgeServiceImpl.java
  src/main/java/com/example/icebutler_server/global/exception/ReturnCode.java
  src/main/java/com/example/icebutler_server/global/resolver/AdminResolver.java
  src/main/java/com/example/icebutler_server/global/resolver/LoginResolver.java
  src/main/java/com/example/icebutler_server/global/util/TokenUtils.java
  src/main/java/com/example/icebutler_server/user/controller/UserAuthController.java
  src/main/java/com/example/icebutler_server/user/controller/UserController.java
  src/main/java/com/example/icebutler_server/user/dto/assembler/UserAssembler.java
  src/main/java/com/example/icebutler_server/user/dto/response/MyNotificationRes.java
  src/main/java/com/example/icebutler_server/user/exception/AccessDeniedUserException.java
  src/main/java/com/example/icebutler_server/user/exception/AlreadyExistNickNameException.java
  src/main/java/com/example/icebutler_server/user/exception/AlreadyWithdrawUserException.java
  src/main/java/com/example/icebutler_server/user/exception/AuthAnnotationIsNowhereException.java
  src/main/java/com/example/icebutler_server/user/exception/InvalidUserNickNameException.java
  src/main/java/com/example/icebutler_server/user/exception/InvalidUserProfileImgKeyException.java
  src/main/java/com/example/icebutler_server/user/exception/ProviderMissingValueException.java
  src/main/java/com/example/icebutler_server/user/exception/TokenExpirationException.java
  src/main/java/com/example/icebutler_server/user/exception/UserEmailMissingValueException.java
  src/main/java/com/example/icebutler_server/user/exception/UserNicknameNotFoundException.java
  src/main/java/com/example/icebutler_server/user/exception/UserNotFoundException.java
  src/main/java/com/example/icebutler_server/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#335 #329 로그인 리졸버 유저 검증 로직 추가
  src/main/java/com/example/icebutler_server/cart/controller/CartController.java
  src/main/java/com/example/icebutler_server/fridge/controller/FridgeController.java
  src/main/java/com/example/icebutler_server/global/exception/ExceptionAdvice.java
  src/main/java/com/example/icebutler_server/global/exception/ReturnCode.java
  src/main/java/com/example/icebutler_server/global/feign/feignClient/RecipeServerClient.java
  src/main/java/com/example/icebutler_server/global/resolver/LoginResolver.java
  src/main/java/com/example/icebutler_server/global/resolver/LoginStatus.java
  src/main/java/com/example/icebutler_server/global/util/TokenUtils.java
  src/main/java/com/example/icebutler_server/global/util/redis/RedisTemplateService.java
  src/main/java/com/example/icebutler_server/global/util/redis/RedisTemplateServiceImpl.java
  src/main/java/com/example/icebutler_server/user/controller/UserAuthController.java
  src/main/java/com/example/icebutler_server/user/repository/UserRepository.java
  src/main/java/com/example/icebutler_server/user/service/UserServiceImpl.java
Labels: 🍽 feature, ♻️ refactor

#337 #336 secretKey 파싱 오류 수정
  src/main/java/com/example/icebutler_server/global/util/TokenUtils.java
Labels: 🚑 hotfix

#342 #338 .DS_Store 캐시 삭제
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/example/.DS_Store
  src/main/java/com/example/icebutler_server/.DS_Store
Labels: ✏️ remove

#343 #334 냉장고 추가 및 정보 수정 API 리팩토링
  build.gradle
  src/main/java/com/example/icebutler_server/fridge/controller/FridgeController.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/AddFridgeReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/EditFridgeReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/FridgeModifyMembersReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/FridgeModifyReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/FridgeRegisterMembersReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/request/FridgeRegisterReq.java
  src/main/java/com/example/icebutler_server/fridge/dto/response/UpdateMembersRes.java
  src/main/java/com/example/icebutler_server/fridge/entity/Fridge.java
  src/main/java/com/example/icebutler_server/fridge/entity/FridgeUser.java
  src/main/java/com/example/icebutler_server/fridge/repository/FridgeUserRepository.java
  src/main/java/com/example/icebutler_server/fridge/service/FridgeService.java
  src/main/java/com/example/icebutler_server/fridge/service/FridgeServiceImpl.java
  src/main/java/com/example/icebutler_server/global/exception/ExceptionAdvice.java
Labels: ♻️ refactor
